### PR TITLE
LRAC-7580 Create macros for ACKeywords and settings navigation

### PR DESCRIPTION
**Pull request by joshitagaki**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Hey @joshitagaki , your code LGTM! 👏🏼 

I just would like to share a suggestion/tip with you, regarding the use of some Texts to perform some navigation/clicks... I've worked before for an internationalization (i18n) team doing a lot of automation, there we need to code a single scripts that had to be executed on several languages, so we had to create our locators without the use of the UI Strings, since for each execution a different value was present in the UI. We know that in our fw we only execute the tests in English, so it will not be a problem, but just sharing my previous experience with you :) 

In your code, we could do some improvements in this regard when you are clicking in the Options (at left) using the UI String options, to avoid this situation, what I did in ACNavigation.macro was to pass a substring/keyword of the URL on the macros and get that element by the @href attribute in the paths instead, so I was able to perform the click in the option I want without the use of UI Strings. This kind of info like the substring/keyword in the URL is something that we call in i18n as a locale independent attribute, so it will be the same regardless of the language the system is set.

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
